services:
  - type: web
    name: edusync
    runtime: docker
    plan: free
    region: singapore
    branch: main
    envVars:
      - key: APP_NAME
        value: EDUSYNC
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: RUN_MIGRATIONS
        value: "true"
      - key: RUN_SEEDER
        value: "true"
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: file
